# server port
server:
  port: 8090

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kosa_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kosa
    password: 1004

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
