# server port
server:
  port: 8090

# database
spring:
  servlet:
    multipart:
      max-file-size: 10MB        # Max size for a single file
      max-request-size: 10MB     # Max size for entire request
      file-size-threshold: 1MB   # Buffer to disk when upload exceeds 1MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kosa_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kosa
    password: 1004

file:
  upload-dir: ${FILE_UPLOAD_DIR:${user.dir}/uploads}  # Defaults to project uploads directory (cross-platform)

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

